# site settings
title: Fluffy Octo Pancake
subtitle: by Anime Society, IIT Kanpur
email: mayantmukul@hotmail.com
description: "A tactical turn-based strategy game made by the elitist faction of AniSoc"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://fluffy-octo-pancake.github.io" # the base hostname & protocol for your site
author: Mayant Mukul
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
